Repository jorgebucaran/superfine, pull requests merged in 2018-07, with the labels that each got.

#137 fix `onupdate` example
  README.md
Labels: DOCS

#142 Update superfine.d.ts
  superfine.d.ts
Labels: TYPINGS

#144 update typings
  superfine.d.ts
Labels: FIX, TYPINGS
