Repository jorgebucaran/superfine, pull requests merged in 2018-03, with the labels that each got.

#100 add null possibility to patch types
  ultradom.d.ts
Labels: FIX, TYPES

#103 Delegate DOM event handlers to common proxy handler.
  README.md
  package.json
  src/h.js
  src/index.js
  src/patch.js
  test/dom.test.js
  test/h.test.js
  test/lifecycle.test.js
  test/recycling.test.js
  test/svg.test.js
  test/ts/index.tsx
  test/ts/tsconfig.json
  ultradom.d.ts
Labels: IMPROVEMENT

#105 fix h types
  ultradom.d.ts
Labels: TYPES
